name: Android Instrumentation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  instrumentation-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [ 30 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Download Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-levels: ${{ matrix.api-level }}
          target: default
          ndk: ''

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Instrumentation Tests
        run: ./gradlew connectedAndroidTest